### ISSUE TITLE
vinfo for current folder

### ISSUE THREAD

**Issue by sed-i** [PietroPasotti/jhack#106]
Would be super handy if vinfo worked for charm libs for the current folder, without needing to deploy the charm.

**Comment by PietroPasotti** [comment]
that's a nice addition, I'll work on it

**Comment by PietroPasotti** [comment]
![image](https://github.com/PietroPasotti/jhack/assets/6230162/a9b99818-8ede-4ca3-bcea-8f098bb671af)
easy peasy
