### ISSUE TITLE
Machine charm detection does not work

### ISSUE THREAD

**Issue by awnns** [PietroPasotti/jhack#51]
In `./helpers.py`, `get_substrate()` is defined as:
```python
def get_substrate(model: str = None) -> Literal["k8s", "machine"]:
    """Attempts to guess whether we're talking k8s or machine."""
    cmd = f'juju show-model{f" {model}" if model else ""} --format=json'
    proc = JPopen(cmd.split())
    raw = proc.stdout.read().decode("utf-8")
    model_info = jsn.loads(raw)

    if not model:
        model = list(model_info)[0]

    model_type = model_info[model]["model-type"]
    if model_type == "caas":
        return "machine"
    elif model_type == "iaas":
        return "k8s"
    else:
        raise ValueError(f"unrecognized model type: {model_type}")
```
This does not work in practice, because our machine charms also report `model-type` as `"iaas"`. A field that should set them apart is `type` which says `"lxd"` for us but I'm not sure I have all bases covered in terms of which values are possible here so I will wait a little with contributing a fix.

**Comment by PietroPasotti** [comment]
Huh. Some juju folk had told me that iaas would be unique to kubernetes. But given what you say it might be safer to filter based on type == 'kubernetes'. 
I'm not sure what the complete list of types is though.

**Comment by PietroPasotti** [comment]
Also see juju-thread on the topic: https://chat.charmhub.io/charmhub/pl/pfq6ky61fjnqzmxjgsta7pejxc

**Comment by awnns** [comment]
In that case I got myself a little confused. There's a little typo where they got switched around.

**Comment by PietroPasotti** [comment]
Oh! You're very much right. Thanks a lot :)
