### ISSUE TITLE
`show-relation` on peer relations with one unit doesn't work

### ISSUE THREAD

**Issue by zmraul** [PietroPasotti/jhack#58]
### Steps to reproduce
Tested on the snap:
1) Deploy just one unit of a charm that creates a peer relation
2) `jhack show-relation app:peers`
```
KeyError: 'related-units'
```

**Comment by PietroPasotti** [comment]
aha, I think I know what that's about. The fact that juju commands can drop keys if the values are empty forces me to write really really defensive code. Uncool but undertandable. Will fix soon

**Comment by PietroPasotti** [comment]
should be fixed on edge as soon as the build completes. thanks for reporting!
