### ISSUE TITLE
KeyError: 'getpwuid(): uid not found

### ISSUE THREAD

**Issue by jamesbeedy** [PietroPasotti/jhack#67]
Hello,

Trying to run any `jhack` command gives:

```
$ jhack --help
Traceback (most recent call last):
  File "/snap/jhack/201/bin/jhack", line 8, in <module>
    sys.exit(main())
  File "/snap/jhack/201/lib/python3.8/site-packages/jhack/main.py", line 19, in main
    from jhack.config import configure
  File "/snap/jhack/201/lib/python3.8/site-packages/jhack/config.py", line 10, in <module>
    USR = pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 115271064'
```

**Comment by PietroPasotti** [comment]
Umh, first time I see that. What environment are you in? multipass VM?
Jhack.config needs to know what user you are in order to expand `~` and find where your jhack config is.

**Comment by jamesbeedy** [comment]
Hey @PietroPasotti, thanks for the swift response.

I have tested this on two systems, with latest stable and edge (revs 201 and 203).

![Screenshot 2023-03-15 at 7 32 41 AM](https://user-images.githubusercontent.com/5590546/225343579-aff15b4c-2b07-4ebe-95ad-b92d21481e93.png)
on the left, my bdx user is a local user, on the right (where jhack is failing) the user is a non-local user (comes from active directory)
![Screenshot 2023-03-15 at 7 33 43 AM](https://user-images.githubusercontent.com/5590546/225343651-f3e9f6ea-9fac-4bac-84b7-8f0f57919112.png)
the system that jhack fails on is the system where the user is a non-local user

**Comment by jamesbeedy** [comment]
![Screenshot 2023-03-15 at 7 43 08 AM](https://user-images.githubusercontent.com/5590546/225345091-16cf060d-f1a7-4c9b-adcc-425212ccc7ca.png)

**Comment by jamesbeedy** [comment]
From mattermost discussion ![Screenshot 2023-03-15 at 7 50 47 AM](https://user-images.githubusercontent.com/5590546/225347463-ac0d2cf1-d601-48e4-89e3-95ed4da1e8ca.png)
