### ISSUE TITLE
Option to disable blinking animation in `jhack nuke`

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [PietroPasotti/jhack#74]
Would it be possible to add an option to disable the blinking animation after running `jhack nuke`?

https://github.com/PietroPasotti/jhack/blob/5003726c3d3f5b478da3b7cfe69c59e75e662b04/jhack/utils/nuke.py#L381

For me, it's difficult to focus on the output of other commands in the terminal when it's blinking, so I often end up `clear`ing my terminal, but then I lose output from the commands before

**Comment by PietroPasotti** [comment]
@carlcsaposs-canonical --> https://github.com/PietroPasotti/jhack/pull/75 if you have time to try it out and review, please :)
