### ISSUE TITLE
`jhack` snap should infer jhack version from installed project

### ISSUE THREAD

**Issue by jamesbeedy** [PietroPasotti/jhack#84]
Currently, the `jhack` version is pinned in the `snapcraft.yaml` and in the `pyproject.toml`.

This is confusing and increases maintenance overhead.

To fix this issue, infer the project version from importlib metadata and set using `snapcraftctl`

**Comment by PietroPasotti** [comment]
I'm not familiar with snapcraftctl, do you have an example snap using this mechanism?

**Comment by PietroPasotti** [comment]
found some docs: 
https://snapcraft.io/docs/using-external-metadata#meta-scriptlet
