### ISSUE TITLE
jhack tail throws `ERROR cannot load ssh client keys`

### ISSUE THREAD

**Issue by DnPlas** [PietroPasotti/jhack#9]
I am not sure if I am missing some configuration step, I have tried following [this](https://discourse.charmhub.io/t/exploring-event-emission-with-jhack-tail/6749) guide.

#### Observed behaviour

Running `jhack tail` throws the following error:

```
WARNING:jhack:JUJU_DATA is None
WARNING:jhack:setting JUJU_DATA to: /home/ubuntu/.local/share/juju/
ERROR cannot load ssh client keys: open /home/ubuntu/.local/share/juju/ssh: permission denied
No events caught.
```

#### Steps to reproduce

```
sudo snap install jhack --channel latest/edge
sudo snap set jhack juju=/snap/bin/juju jujudata=/home/USERNAME/.local/share/juju/ # my username is ubuntu
juju model-config logging-config="<root>=WARNING;unit=DEBUG"
juju deploy kubeflow --channel cfk-1.6/beta --trust # large bundle
jhack tail
```

**Comment by PietroPasotti** [comment]
Not sure what's going on exactly, but I'm working these days on polishing up the snap and release it with strict confinement. That should hopefully fix this kind of issues.
To get around it for now you should install from sources.

**Comment by PietroPasotti** [comment]
PS. the strict confinement snap release is taking longer than expected, I'd advise to install from sources until then

**Comment by PietroPasotti** [comment]
@DnPlas the strictly confined snap is available! could you try it out and see if the issue is solved?
