### ISSUE TITLE
Watching relations does not show new units

### ISSUE THREAD

**Issue by gboutry** [PietroPasotti/jhack#94]
Using `juju show-relation --watch` on a relation does not show units added.

Workaround is to exit jhack and re-run the command.

As a reference, the command actually ran:
```
jhack show-relation --show-juju-keys barbican:secrets vault:secrets --watch
```

**Comment by PietroPasotti** [comment]
good catch! there is an issue with caching. In an earlier effort to reduce the flickering and speed up jhack, I overcached some juju status calls resulting in unit additions not being detected.
Should be an easy fix (but performance will decrease until I find some other way to work around the limitation).
